#Makefile
#By Wouter van Akkeren


priority: ../../gen/analysis/output/Linearregression.csv


#step1
../../gen/analysis/output/Linearregression.csv: ../../gen/analysis/input/final_dataset_housemarket.csv linear_regression.R
	Rscript linear_regression.R
